import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/lib/fonts";
import I18nProvider from "@/locales/i18nprovider";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${poppins.variable}`} lang="en">
      <body
       
      >
        <I18nProvider>
        {children}
        </I18nProvider>
      </body>
    </html>
  );
}
